AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Parameters:
  Env:
    Type: String
    Default: api

Resources:
  HttpApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      CorsConfiguration: "True"

  SearchFunction:
    Type: AWS::Serverless::Function
    Properties:
      AutoPublishAlias: !Ref Env
      CodeUri: dist/search.zip
      Handler: hello
      MemorySize: 256
      Timeout: 30
      Runtime: provided
      Events:
        HttpApi:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Method: GET
            Path: /search
            PayloadFormatVersion: "1.0"
